
sudo: false
language: c
compiler:
- gcc
os:
- linux
before_script:
- git clone https://github.com/json-c/json-c.git
- cd json-c
- ./configure --prefix=../lib/json-c
- make install
- cd ..
script:
- cmake .
- make all

