
sudo: true
language: c
compiler:
- gcc
os:
- linux
before_install:
- git clone git://git.cryptomilk.org/projects/cmocka.git
- cd cmocka && mkdir build && cd build
- cmake .. && make -j2 && sudo make install
- cd ../..

- git clone https://github.com/json-c/json-c.git
- cd json-c
- cmake . && make -j2 && sudo make install

- cd ..
script:
- cmake .
- make all

